services:
  backend:
    build:
      context: ./backend
    container_name: secret_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/djangoApp:/app
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: secret_ui
    ports:
      - "3000:80"
    depends_on:
      - backend

  redis:
    image: "redis:alpine"
    container_name: redis_db
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_gui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis