# Generated by Django 5.2.6 on 2025-09-10 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorials', to='biblioteca.author')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editorials',
            },
        ),
    ]
